language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_Guschin_Lab
  - make -j
  - ./vectortest/vectortest
  - ./queuetest/queuetest
  - ./stacktest/stacktest
  - ./multistacktest/multistacktest
  - ./listtest/listtest
  - ./stacklisttest/stacklisttest
  - ./arrlisttest/arrlisttest
  - ./polynomtest/polynomtest
  - ./tablestest/tablestest
  - ./plextest/plextest
notifications:
  email: false
