language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../381706-2_Guschin_Lab
  - make -j
  - ./queuetest/queuetest
  - ./stacktest/stacktest
notifications:
  email: false
